## Configuracion de Instancia
server:
  port: 8082
  error:
    include-stacktrace: on_param

## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-library-loans

## Configuracion de Spring
spring:
  application:
    name: ms-library-loans
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3307/laboratorio}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:mysql}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

## Configuracion secundaria (custom)
getBook:
  url: http://ms-library-books/books/%s
